# Analazing the Casablanca Stock Exchange data project

# Task 1 : Collecting Data

In [6]:
from bs4 import BeautifulSoup
import pandas as pd

#We have taken data from the sector "Construction and building materials".
#We have choosen the following Instruments : Afric Industries SA as "afr_ind", Colorado as "colorado",
#Jet Contractors as "jet_con",Lafargeholcim MAR as "lafarge" and TGCC S.A as "tgcc".

def scrapper(file_name):
#file_name is the name of the instrument.
#The dictionary "dic_files" contains the names of instrument as keys and the value as a path to the file containing the data.
    
    dic_files={"afr_ind":"data_py_pro/Africa_industries.aspx",
           "colorado":"data_py_pro/colorado.aspx",
           "jet_con":"data_py_pro/Jet_contractors.aspx",
           "lafarge":"data_py_pro/Lafarge_holcim.aspx",
           "tgcc":"data_py_pro/Tgcc.aspx"}
    
#we assign use"with open() as" so it closes automatically
    with open(dic_files[file_name],"r") as myfile:
#We read the data in the file and we store it in a variable, use globals() to make the string "file_name" become variable file_name
        globals()[file_name]=myfile.read() 
#We store the content after applying BeautifulSoup in final_file
        final_file=BeautifulSoup(globals()[file_name],'lxml')  

    list_of_columns = ["date","closing","adjusted","evolution","quantity","volume"] 
    data=[]
#Number of the days existing in data is 733 day and 6 jump lap is to go to the next date.
    for i in range(0,4386,6): 
        data.append([final_file.find_all("span")[i].get_text(),
        float(final_file.find_all("span")[i+1].get_text().replace(",",".")),
        float(final_file.find_all("span")[i+2].get_text().replace(",",".")),
        float(final_file.find_all("span")[i+3].get_text().replace(",",".")),
        float(final_file.find_all("span")[i+4].get_text().replace(",",".")),
        float(final_file.find_all("span")[i+5].get_text().replace(",","."))])
        
#Now let's transforme it to a csv file
    data_df= pd.DataFrame(data,columns=list_of_columns)        
    data_csv= data_df.to_csv("{}.csv".format(file_name))
    return data_csv

In [7]:
scrapper("afr_ind")

           date  closing  adjusted  evolution  quantity    volume
0    01/12/2022   338.00    338.00       0.07       6.0   2028.00
1    30/11/2022   337.75    337.75       0.00       0.0      0.00
2    29/11/2022   337.75    337.75       0.13       9.0   3039.75
3    28/11/2022   337.30    337.30      -0.79      34.0  11471.90
4    25/11/2022   340.00    340.00       0.00       0.0      0.00
..          ...      ...       ...        ...       ...       ...
726  09/01/2020   288.00    288.00       0.00       0.0      0.00
727  08/01/2020   288.00    288.00       0.00       0.0      0.00
728  07/01/2020   288.00    288.00       0.00       0.0      0.00
729  06/01/2020   288.00    288.00       0.00       0.0      0.00
730  03/01/2020   288.00    288.00       0.00       0.0      0.00

[731 rows x 6 columns]

# Task 2 : Creating class stock

In [8]:
import matplotlib.pyplot as plt
import numpy as np

class Stock():
    

    def __init__(self,name):
#Constructor of the Stock class.
        self.name = name
#The method scrapper() will create the data for us, then turn it into pandas DataFrame.
        scrapper(name)
        self.data=pd.read_csv(name+".csv")